import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import LinearProgress from "@mui/material/LinearProgress";

import "./globals.css";
import React from "react";
import ThemeProvider from "@/theme/provider";
import Rtl from "@/theme/rtl";
import { iranYekan } from "@/theme/fonts";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<AppRouterCacheProvider options={{ enableCssLayer: true }}>
				<React.Suspense fallback={<LinearProgress />}>
					<ThemeProvider>
						<Rtl>
							<body
								className={`antialiased ${iranYekan.variable} ${iranYekan.className}`}
							>
								{children}
							</body>
						</Rtl>
					</ThemeProvider>
				</React.Suspense>
			</AppRouterCacheProvider>
		</html>
	);
}
