import type { Metadata } from 'next';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import LinearProgress from '@mui/material/LinearProgress';
import InitColorSchemeScript from '@mui/material/InitColorSchemeScript';

import './globals.css';
import React from 'react';
import ThemeProvider from '@/theme/provider';
import Rtl from '@/theme/rtl';
import { iranYekan } from '@/theme/fonts';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import Script from 'next/script';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();
  const locale = await getLocale();
  return (
    <html
      lang={locale}
      suppressHydrationWarning
    >
      <body
        dir='rtl'
        className={`antialiased ${iranYekan.variable} ${iranYekan.className}`}
      >
        <InitColorSchemeScript attribute='class' />
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <React.Suspense fallback={<LinearProgress />}>
            <Rtl>
              <ThemeProvider>
                <NextIntlClientProvider messages={messages}>
                  {children}
                </NextIntlClientProvider>
              </ThemeProvider>
            </Rtl>
          </React.Suspense>
        </AppRouterCacheProvider>
        <Script src='https://cdn.jsdelivr.net/npm/swiper@11/swiper-element-bundle.min.js' />
      </body>
    </html>
  );
}
